module.exports = {
    plugins: [
        'stylelint-order',
    ],
    'rules': {
        'order/order': [
            'less-mixins',
            'at-variables',
            'declarations',
            'at-rules',
            'rules',

            // Blocks order stubs (discussion needed):
            // {
            //     type: 'at-rule',
            //     name: 'keyframes',
            // },
            // {
            //     type: 'at-rule',
            //     name: 'media',
            // },
            // {
            //  type: 'rule',
            //  selector: '^&:(hover|focus|active)$',
            // },
            // {
            //  type: 'rule',
            //  selector: '^&--[\\w-]+$',
            //  description: 'BEM modifiers, e. g. &--wide',
            // },
            // {
            //  type: 'rule',
            //  selector: '^&\\.[\\w-]+$',
            //  description: 'E. g. &.is-open',
            // },
            // {
            //  type: 'rule',
            //  selector: '^&\\[.+\\]$',
            //  description: 'E. g. &[disabled]',
            // },
            // {
            //  type: 'rule',
            //  selector: '^&:(before|after)$',
            // },
            // {
            //  type: 'rule',
            //  selector: '^&::\\w+$',
            //  description: 'Pseudo-elements',
            // },
        ],
        'order/properties-order': [
            [
                'content',
                'position',
                'top',
                'right',
                'bottom',
                'left',
                'z-index',
                'display',
                'visibility',
                'flex',
                'flex-grow',
                'flex-shrink',
                'flex-basis',
                'flex-direction',
                'flex-flow',
                'flex-wrap',
                'align-content',
                'align-items',
                'align-self',
                'justify-content',
                'order',
                'float',
                'clear',
                'overflow',
                'overflow-x',
                'overflow-y',
                'overflow-scrolling',
                'clip',
                'box-sizing',
                'min-width',
                'min-height',
                'max-width',
                'max-height',
                'width',
                'height',
                'margin',
                'margin-top',
                'margin-right',
                'margin-bottom',
                'margin-left',
                'padding',
                'padding-top',
                'padding-right',
                'padding-bottom',
                'padding-left',
                'outline',
                'outline-width',
                'outline-style',
                'outline-color',
                'outline-offset',
                'border',
                'border-spacing',
                'border-collapse',
                'border-width',
                'border-style',
                'border-color',
                'border-top',
                'border-top-width',
                'border-top-style',
                'border-top-color',
                'border-right',
                'border-right-width',
                'border-right-style',
                'border-right-color',
                'border-bottom',
                'border-bottom-width',
                'border-bottom-style',
                'border-bottom-color',
                'border-left',
                'border-left-width',
                'border-left-style',
                'border-left-color',
                'border-radius',
                'border-top-left-radius',
                'border-top-right-radius',
                'border-bottom-right-radius',
                'border-bottom-left-radius',
                'border-image',
                'border-image-source',
                'border-image-slice',
                'border-image-width',
                'border-image-outset',
                'border-image-repeat',
                'border-top-image',
                'border-right-image',
                'border-bottom-image',
                'border-left-image',
                'border-corner-image',
                'border-top-left-image',
                'border-top-right-image',
                'border-bottom-right-image',
                'border-bottom-left-image',
                'background',
                'background-color',
                'background-image',
                'background-attachment',
                'background-position',
                'background-position-x',
                'background-position-y',
                'background-clip',
                'background-origin',
                'background-size',
                'background-repeat',
                'box-decoration-break',
                'box-shadow',
                'color',
                'table-layout',
                'caption-side',
                'empty-cells',
                'list-style',
                'list-style-position',
                'list-style-type',
                'list-style-image',
                'quotes',
                'counter-increment',
                'counter-reset',
                '-ms-writing-mode',
                'vertical-align',
                'text-align',
                'text-align-last',
                'text-decoration',
                'text-emphasis',
                'text-emphasis-position',
                'text-emphasis-style',
                'text-emphasis-color',
                'text-indent',
                'text-justify',
                'text-outline',
                'text-transform',
                'text-wrap',
                'text-overflow',
                'text-overflow-ellipsis',
                'text-overflow-mode',
                'text-shadow',
                'white-space',
                'word-spacing',
                'word-wrap',
                'word-break',
                'overflow-wrap',
                'tab-size',
                'hyphens',
                'letter-spacing',
                'font',
                'font-weight',
                'font-style',
                'font-variant',
                'font-size-adjust',
                'font-stretch',
                'font-size',
                'font-family',
                'src',
                'line-height',
                'interpolation-mode',
                'opacity',
                'filter',
                'resize',
                'cursor',
                'nav-index',
                'nav-up',
                'nav-right',
                'nav-down',
                'nav-left',
                'transition',
                'transition-delay',
                'transition-timing-function',
                'transition-duration',
                'transition-property',
                'transform',
                'transform-origin',
                'animation',
                'animation-name',
                'animation-duration',
                'animation-play-state',
                'animation-timing-function',
                'animation-delay',
                'animation-iteration-count',
                'animation-direction',
                'animation-fill-mode',
                'pointer-events',
                'unicode-bidi',
                'direction',
                'columns',
                'column-span',
                'column-width',
                'column-count',
                'column-fill',
                'column-gap',
                'column-rule',
                'column-rule-width',
                'column-rule-style',
                'column-rule-color',
                'break-before',
                'break-inside',
                'break-after',
                'page-break-before',
                'page-break-inside',
                'page-break-after',
                'orphans',
                'widows',
                'zoom',
                'max-zoom',
                'min-zoom',
                'user-zoom',
                'orientation',
                'user-select',
                'fill',
                'stroke'
            ],
            {
                unspecified: 'bottom'
            }
        ],

        // Color
        'color-hex-length': 'short',
        'color-hex-case': 'lower',
        'color-no-invalid-hex': true,

        // Font
        'font-family-name-quotes': 'always-where-recommended',

        // Function
        'function-calc-no-unspaced-operator': true,
        'function-comma-space-after': 'always',
        'function-comma-space-before': 'never',
        'function-linear-gradient-no-nonstandard-direction': true,
        'function-max-empty-lines': 0,
        'function-name-case': 'lower',
        'function-parentheses-space-inside': 'never',
        'function-whitespace-after': 'always',

        // Number
        'number-leading-zero': 'never',
        'number-no-trailing-zeros': true,

        // String
        'string-no-newline': true,
        'string-quotes': 'single',

        // Length
        'length-zero-no-unit': true,

        // Time

        // Unit
        'unit-blacklist': ['pt'],
        'unit-case': 'lower',
        'unit-whitelist': ['px', '%', 'vh', 'vw', 's', 'rem', 'em', 'ex', 'vmin', 'vmax', 'deg'],

        // Value
        'value-keyword-case': 'lower',
        'value-no-vendor-prefix': true,
        'value-list-comma-space-after': 'always',
        'value-list-comma-space-before': 'never',

        // Property
        'shorthand-property-no-redundant-values': true,
        'property-case': 'lower',
        'property-no-unknown': [true, {
            'severity': 'warning'
        }],
        'property-no-vendor-prefix': true,

        // Declaration
        'declaration-bang-space-after': 'never',
        'declaration-bang-space-before': 'always',
        'declaration-colon-space-before': 'never',
        'declaration-colon-space-after': 'always',
        'declaration-empty-line-before': 'never',

        // Declaration block
        'declaration-block-no-duplicate-properties': true,
        'declaration-block-no-redundant-longhand-properties': true,
        'declaration-block-no-shorthand-property-overrides': true,
        'declaration-block-semicolon-newline-after': 'always',
        'declaration-block-semicolon-space-before': 'never',

        // Block
        'block-closing-brace-empty-line-before': 'never',
        'block-closing-brace-newline-after': 'always',
        'block-closing-brace-newline-before': 'always',
        'block-no-empty': true,
        'block-opening-brace-newline-after': 'always',

        // Selector
        'selector-attribute-brackets-space-inside': 'never',
        'selector-attribute-operator-space-after': 'never',
        'selector-attribute-operator-space-before': 'never',
        'selector-attribute-quotes': 'always',
        // 'selector-class-pattern': [], // TODO: pattern for class selectors according BEM naming
        'selector-combinator-space-after': 'always',
        'selector-combinator-space-before': 'always',
        'selector-descendant-combinator-no-non-space': true,
        // 'selector-id-pattern': '', TODO: pattern for camelCase ids
        'selector-max-compound-selectors': 3,
        'selector-no-vendor-prefix': true,
        'selector-pseudo-class-case': 'lower',
        'selector-pseudo-class-no-unknown': true,
        'selector-pseudo-class-parentheses-space-inside': 'never',
        'selector-pseudo-element-case': 'lower',
        'selector-pseudo-element-colon-notation': 'double',
        'selector-pseudo-element-no-unknown': true,
        'selector-type-case': 'lower',
        'selector-type-no-unknown': true,
        'selector-max-empty-lines': 0,

        // Selector list
        'selector-list-comma-newline-after': 'always',

        // Rule
        'rule-empty-line-before': ['always', {
            except: ['first-nested'],
            ignore: ['after-comment']
        }],

        // Media feature
        'media-feature-colon-space-after': 'always',
        'media-feature-colon-space-before': 'never',
        'media-feature-name-case': 'lower',
        'media-feature-name-no-unknown': true,
        'media-feature-parentheses-space-inside': 'never',
        'media-feature-range-operator-space-after': 'always',
        'media-feature-range-operator-space-before': 'always',
        'media-query-list-comma-newline-after': 'always-multi-line',
        'media-query-list-comma-space-after': 'always-single-line',
        'media-query-list-comma-space-before': 'never',

        // At-rule
        'at-rule-empty-line-before': ['always', {
            except: ['after-same-name', 'first-nested'],
            ignore: ['after-comment']
        }],
        'at-rule-name-case': 'lower',
        'at-rule-name-space-after': 'always-single-line',
        'at-rule-no-unknown': true,
        'at-rule-no-vendor-prefix': true,
        'at-rule-semicolon-newline-after': 'always',
        'at-rule-semicolon-space-before': 'never',

        // Comment
        'comment-no-empty': true,
        'comment-whitespace-inside': 'always',

        // General / Sheet
        'indentation': 4,
        'max-empty-lines': 2,
        'max-nesting-depth': 4,
        'no-duplicate-selectors': true,
        'no-eol-whitespace': true,
        'no-extra-semicolons': true,
        'no-unknown-animations': true,
        'no-missing-end-of-source-newline': true
    }
};
